### ISSUE TITLE
Jobs under QA review not showing up in Agenda

### ISSUE THREAD

**Issue by carlosmiranda** [zerocracy/farm#1341]
One of my jobs is under QA review as of writing (see https://github.com/zerocracy/farm/pull/1328#issuecomment-402615857). However, it's not showing up in my agenda:

![image](https://user-images.githubusercontent.com/1917892/42305452-95af751e-805d-11e8-9400-eb91dfd9dc1d.png)

This was supposed to be fixed in #911, with the reviewer being displayed, but it seems to be not quite completely fixed yet.

**UPDATE**: See https://github.com/zerocracy/farm/issues/1341#issuecomment-405849570 for the cause of the bug.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1341](https://github.com/zerocracy/farm/issues/1341) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by carlosmiranda** [comment]
@g4s8 this happened again in #1166, it's under QA review but not showing up in my Agenda. This is very inconsistent, a couple of days ago some of my jobs did show up in the list with the QA reviewer.

You might be able to look at claims and other project artifacts to see if there's any pattern.

**Comment by g4s8** [comment]
@carlosmiranda there are no errors in footprint:
```
    1910749580 3min "Reputation was updated" (0.25.4)
    reason: Quality review completed
    issue: 1166
    minutes: 8
    repo: zerocracy/farm
    login: ypshenychka
    token: github;zerocracy/farm;1166;403732410
    quality: good
    points: 8
    comment: 403732410
    job: gh:zerocracy/farm#1166
    flow: Complete QA review; Make payment; Award points were added

    1910749569 3min "Reputation was updated" (0.25.4)
    reason: Order was finished, quality is "good"
    issue: 1166
    minutes: 38
    repo: zerocracy/farm
    login: carlosmiranda
    token: github;zerocracy/farm;1166;403732410
    quality: good
    points: 38
    comment: 403732410
    job: gh:zerocracy/farm#1166
    cash:
    flow: Complete QA review; Make payment; Award points were added

    1910749567 4min "Send zold" (0.25.4)
    reason: Quality review completed
    amount:
    issue: 1166
    minutes: 8
    repo: zerocracy/farm
    login: ypshenychka
    token: github;zerocracy/farm;1166;403732410
    quality: good
    recipient: ypshenychka
    comment: 403732410
    job: gh:zerocracy/farm#1166
    flow: Complete QA review; Make payment

    1910749565 4min "Payment was added to debts" (0.25.4)
    reason: Quality review completed
    amount:
    issue: 1166
    minutes: 8
    repo: zerocracy/farm
    login: ypshenychka
    token: github;zerocracy/farm;1166;403732410
    quality: good
    comment: 403732410
    job: gh:zerocracy/farm#1166
    flow: Complete QA review; Make payment

    1910748555 4min "Award points were added" (0.25.4)
    reason: Quality review completed
    issue: 1166
    minutes: 8
    repo: zerocracy/farm
    login: ypshenychka
    token: github;zerocracy/farm;1166;403732410
    quality: good
    points: 8
    comment: 403732410
    job: gh:zerocracy/farm#1166
    flow: Complete QA review; Make payment

    1910748552 4min "Equity transferred" (0.25.4)
    reward:
    reason: Order was finished, quality is "good"
    issue: 1166
    minutes: 38
    repo: zerocracy/farm
    login: carlosmiranda
    token: github;zerocracy/farm;1166;403732410
    quality: good
    vesting_rate:
    comment: 403732410
    job: gh:zerocracy/farm#1166
    cash:
    flow: Complete QA review; Make payment

    1910748550 4min "Send zold" (0.25.4)
    reason: Order was finished, quality is "good"
    amount:
    issue: 1166
    minutes: 38
    repo: zerocracy/farm
    login: carlosmiranda
    token: github;zerocracy/farm;1166;403732410
    quality: good
    recipient: carlosmiranda
    comment: 403732410
    job: gh:zerocracy/farm#1166
    cash:
    flow: Complete QA review; Make payment

    1910748548 4min "Payment was added to debts" (0.25.4)
    reason: Order was finished, quality is "good"
    amount:
    issue: 1166
    minutes: 38
    repo: zerocracy/farm
    login: carlosmiranda
    token: github;zerocracy/farm;1166;403732410
    quality: good
    comment: 403732410
    job: gh:zerocracy/farm#1166
    cash:
    flow: Complete QA review; Make payment

    1910747547 5min "Award points were added" (0.25.4)
    reason: Order was finished, quality is "good"
    issue: 1166
    minutes: 38
    repo: zerocracy/farm
    login: carlosmiranda
    token: github;zerocracy/farm;1166;403732410
    quality: good
    points: 38
    comment: 403732410
    job: gh:zerocracy/farm#1166
    cash:
    flow: Complete QA review; Make payment

    1910747546 5min "Make payment" (0.25.4)
    reason: Quality review completed
    issue: 1166
    minutes: 8
    repo: zerocracy/farm
    login: ypshenychka
    token: github;zerocracy/farm;1166;403732410
    quality: good
    comment: 403732410
    job: gh:zerocracy/farm#1166
    flow: Complete QA review

    1910747545 5min "Quality review completed" (0.25.4)
    issue: 1166
    repo: zerocracy/farm
    login: ypshenychka
    token: github;zerocracy/farm;1166;403732410
    quality: good
    comment: 403732410
    job: gh:zerocracy/farm#1166
    flow: Complete QA review

    1910747544 5min "Agenda was updated" (0.25.4)
    issue: 1166
    repo: zerocracy/farm
    login: ypshenychka
    token: github;zerocracy/farm;1166;403732410
    quality: good
    comment: 403732410
    job: gh:zerocracy/farm#1166
    flow: Complete QA review

    1910747543 5min "Make payment" (0.25.4)
    reason: Order was finished, quality is "good"
    issue: 1166
    minutes: 38
    repo: zerocracy/farm
    login: carlosmiranda
    token: github;zerocracy/farm;1166;403732410
    quality: good
    comment: 403732410
    job: gh:zerocracy/farm#1166
    cash:
    flow: Complete QA review

    1910747542 5min "Complete QA review" (0.25.4)
    issue: 1166
    author: ypshenychka
    repo: zerocracy/farm
    token: github;zerocracy/farm;1166;403732410
    quality: good
    comment: 403732410
    job: gh:zerocracy/farm#1166

    1910555406 2hr "Check job status" (0.25.3)
    issue: 1166
    author: carlosmiranda
    repo: zerocracy/farm
    token: github;zerocracy/farm;1166;403708992
    comment: 403708992
    job: gh:zerocracy/farm#1166

    1902163969 10hr "Job removed from WBS" (0.25.2)
    reason: Job was closed, order is finished
    login: carlosmiranda
    token: github;zerocracy/farm;1166
    job: gh:zerocracy/farm#1166
    age: 9229
    flow: Close job; Finish order; Order was finished; Remove job from WBS

    1902161944 10hr "Remove job from WBS" (0.25.2)
    reason: Job was closed, order is finished
    login: carlosmiranda
    token: github;zerocracy/farm;1166
    job: gh:zerocracy/farm#1166
    age: 9229
    flow: Close job; Finish order; Order was finished

    1902161943 10hr "Speed was updated" (0.25.2)
    reason: Job was closed, order is finished
    login: carlosmiranda
    token: github;zerocracy/farm;1166
    job: gh:zerocracy/farm#1166
    age: 9229
    flow: Close job; Finish order; Order was finished

    1902161942 10hr "Agenda was updated" (0.25.2)
    reason: Job was closed, order is finished
    login: carlosmiranda
    token: github;zerocracy/farm;1166
    job: gh:zerocracy/farm#1166
    age: 9229
    flow: Close job; Finish order; Order was finished

    1902161940 10hr "Agenda was updated" (0.25.2)
    reason: start_qa_review
    minutes: 30
    bonus:
    login: ypshenychka
    token: github;zerocracy/farm;1166
    job: gh:zerocracy/farm#1166
    cash:
    flow: Close job; Finish order; Start QA review

    1902161939 10hr "Order was finished" (0.25.2)
    reason: Job was closed, order is finished
    login: carlosmiranda
    token: github;zerocracy/farm;1166
    job: gh:zerocracy/farm#1166
    flow: Close job; Finish order
    age: 9229

    1902161938 10hr "Start QA review" (0.25.2)
    reason: Job was closed, order is finished
    minutes: 30
    bonus:
    login: carlosmiranda
    token: github;zerocracy/farm;1166
    job: gh:zerocracy/farm#1166
    cash:
    flow: Close job; Finish order

    1902161937 10hr "Finish order" (0.25.2)
    reason: Job was closed, order is finished
    token: github;zerocracy/farm;1166
    job: gh:zerocracy/farm#1166
    flow: Close job

    1902146819 10hr "Close job" (0.25.2)
    reason: GitHub issue was closed
    author: krzyk
    job: gh:zerocracy/farm#1166
    token: github;zerocracy/farm;1166
```
